Experiment Initialization failure handling
dice-group/gerbil pull request #453
Opened 2024-05-31 08:03 UTC by arjanoop

Experiment Initialization failure handling

Resolves: [Issue 420](https://github.com/dice-group/gerbil/issues/420)

2024-06-03 16:00 UTC, MichaelRoeder requested changes
I think that it is not good practice to return JSON as content type if the message actually does not contain JSON. Please look at the comments in the code for more details.

2024-06-03 16:00 UTC, MichaelRoeder commented on src/main/java/org/aksw/gerbil/web/response/execution/ExperimentExecutionResponse.java
> +public class ExperimentExecutionResponse {
Please add javadoc comments.

2024-06-06 10:01 UTC, arjanoop commented on src/main/java/org/aksw/gerbil/exceptions/FaultyConfigurationException.java
> +public class FaultyConfigurationException extends RuntimeException{
Added Javadocs

2024-06-06 10:02 UTC, arjanoop commented on src/main/java/org/aksw/gerbil/web/MainController.java
> +    @GetMapping(value = "/execute", produces = MediaType.APPLICATION_JSON_VALUE)
Removed

2024-06-06 10:02 UTC, arjanoop commented on src/main/java/org/aksw/gerbil/web/MainController.java
> +    @ResponseBody
removed

2024-06-06 10:03 UTC, arjanoop commented on src/main/java/org/aksw/gerbil/web/MainController.java
> +    public ResponseEntity<?> execute(@RequestParam(value = "experimentData") String experimentData) {
Refactored to `ResponseEntity<String>`

2024-06-06 10:04 UTC, arjanoop commented on src/main/java/org/aksw/gerbil/web/MainController.java
> +        return new ResponseEntity<>(experimentId, HttpStatus.OK);
Updated the response accordingly 
`ResponseEntity.ok().contentType(MediaType.TEXT_HTML).body(experimentId);`
and similarly for other scenarios with content type `contentType(MediaType.APPLICATION_JSON)`

2024-06-06 10:08 UTC, arjanoop commented on src/main/java/org/aksw/gerbil/web/MainController.java
> +                return new ResponseEntity<>(new ExperimentExecutionResponse(experimentId,e.getMessage()), HttpStatus.BAD_REQUEST);
Yes, added `jackson.databind.ObjectMapper` configuration for generating `json`

2024-06-06 10:08 UTC, arjanoop commented on src/main/java/org/aksw/gerbil/web/response/execution/ExperimentExecutionResponse.java
> +public class ExperimentExecutionResponse {
added javadoc

2024-06-07 09:40 UTC, MichaelRoeder commented on src/main/java/org/aksw/gerbil/web/MainController.java
> +        return new ResponseEntity<>(experimentId, HttpStatus.OK);
TEXT_HTML is slightly misleading, or? Wouldn't `text/plain` be better?
Apart from that, it sound good to me.

2024-06-07 09:43 UTC, MichaelRoeder requested changes
I think `text/plain` would be the better media type when returning the plain experiment ID.

2024-06-07 10:04 UTC, arjanoop commented on src/main/java/org/aksw/gerbil/web/MainController.java
> +        return new ResponseEntity<>(experimentId, HttpStatus.OK);
Refactored it to `return ResponseEntity.ok().contentType(MediaType.TEXT_PLAIN).body(experimentId);`

2024-06-07 10:51 UTC, MichaelRoeder approved these changes
LGTM

2024-06-07 10:51 UTC, merged